Added A sub-menu to change the types of Font and Font-Styles
HaikuArchives/DeskNotes pull request #25
Opened 2023-03-12 15:55 UTC by BarmenduC

A Menu has been added into the already existing context menu listing various font-families and font-styles that can be used in the note. This caters to #8 and partially to #9 . A few fixes still need to be carried out (would probably be working upon that shortly) .

2023-03-12 16:55 UTC, humdingerb requested changes
* Please use the haiku coding style, as does the rest of the code. There's haiku-format in HaikuDepot that can help with that. I commented a few things, but there are more violations. Also remove additionally inserted newlines.
* The current font menu items aren't checkmarked.
* The replicated view doesn't show the text with the set font.
* Please squash related commits before submitting a PR.

2023-03-12 16:55 UTC, humdingerb commented on DeskNoteView.cpp
> +
Remove stray newlines.

2023-03-12 16:55 UTC, humdingerb commented on DeskNoteView.cpp
> +	BAlert 				*alert;
Let's keep the style without tabs and added newlines.

2023-03-12 16:55 UTC, humdingerb commented on DeskNoteView.cpp
> +	//BFont 			currentFont;
Remove commented out code (here and below).

2023-03-12 16:55 UTC, humdingerb commented on DeskNoteView.cpp
> +		case FONT_FAMILY: {
Keep to the coding style. Opening bracket in new line.

2023-03-12 16:55 UTC, humdingerb commented on DeskNoteView.cpp
> +			msg->FindPointer ("source", &ptr);
Keep to the coding style. No space before opening brackets.

2023-03-12 16:55 UTC, humdingerb commented on DeskNoteView.cpp
> +			fontMenu->SetRadioMode (true);	// I can set only one item as "in use"
Don't comment the obvious. Below too.

2023-03-12 16:55 UTC, humdingerb commented on DeskNoteView.cpp
> +	styleMenu = new BMenu(B_TRANSLATE("Font Style"));
Sentence casing. Though just "Font" would be enough, I suppose.

2023-03-12 16:55 UTC, humdingerb commented on DeskNoteView.cpp
> +	menuItem = styleMenu->FindItem("Black");
Why hardcode "Black" to checkmark?

2023-03-12 17:30 UTC, BarmenduC commented
> * Please use the haiku coding style, as does the rest of the code. There's haiku-format in HaikuDepot that can help with that. I commented a few things, but there are more violations. Also remove additionally inserted newlines.
> * The current font menu items aren't checkmarked.
> * The replicated view doesn't show the text with the set font.
> * Please squash related commits before submitting a PR.

Before performing the code-style cleanup, I'll read up the haiku coding style completely. Would perform the clean up soon enough.

Just to make sure, the tab style for variable declaration is to be dropped everywhere (even in header files) or just inside this file?

The stuff that I mentioned that is still remaining to be fixed are namely these two - 

1. Changed Font not appearing in replicants
2. Checkmark not appearing in-front of selected font

I had planned to keep working upon these issues after this PR gets merged, and to mention these 2 as separate issues so that, in case I am incapable of making it work, someone else can take up the work later. Would that be okay?

2023-03-12 18:19 UTC, humdingerb commented
> Just to make sure, the tab style for variable declaration is to be dropped everywhere (even in header files) or just inside this file?

Just in the cpp file you changed.

> 1. Changed Font not appearing in replicants
> 2. Checkmark not appearing in-front of selected font
>
> I had planned to keep working upon these issues after this PR gets merged, and to mention these 2 as separate issues so that, in case I am incapable of making it work, someone else can take up the work later. Would that be okay?

I suppose so.
BTW, I recommend getting familiar with using 'git' from the commandline and using feature branches (see https://github.com/haikuports/haikuports/wiki/DevelopmentModel for an explanation). It's much more powerful and even convenient, once you get used to it.

2023-03-13 06:01 UTC, BarmenduC commented
Requested changes have been mostly fixed. Will be keeping my out for more code-style fixes while I keep working upon  this further.

2023-03-14 06:23 UTC, humdingerb requested changes
Please have another look at the coding style at https://www.haiku-os.org/development/coding-guidelines . As mentioned, "haiku-format" from HaikuDepot can help you.

* Curly brackets at the end of "switch" statements
* Same for "for" and "if" conditions
* Space after "for", "if" etc.
* Space around operators ( =, >= etc)

2023-03-14 06:26 UTC, humdingerb requested changes

2023-03-14 06:26 UTC, humdingerb commented on DeskNoteView.cpp
> +			{
Curly bracket at the end of previous line.

2023-03-14 06:26 UTC, humdingerb commented on DeskNoteView.cpp
> +	font_family	plainFamily, family;
Space insted of tab.

2023-03-14 06:26 UTC, humdingerb commented on DeskNoteView.cpp
> +	{
Curly bracket at the end of previous line.

2023-03-14 23:31 UTC, BarmenduC commented
Manual code-style-fixes performed and .haiku-format added

2023-03-15 14:02 UTC, humdingerb requested changes
Much better. :)
Please remove the haiku.format file. It's only needed somewhere in the folder tree when executing the haiku-format tool.
There are quite a few stray whitespaces around. I recommend installing Koder and "Highlight trailing whitespaces" in its settings. Then they are easily to spot. Maybe even try "Trim trailing whitespaces" from its "Edit" menu.

2023-03-15 14:02 UTC, humdingerb commented on DeskNoteView.cpp
> +			const char* extraCopyrights[] =
Opening curly backet is missing.

2023-03-15 14:02 UTC, humdingerb commented on DeskNoteView.cpp
> +
Between every case-statement, there's now a tab. Please remove, no empty line needed between cases.

2023-03-15 16:29 UTC, BarmenduC commented
Changes performed :-
1. Removed .haiku-format
2. Trimmed trailing whitespaces using Koder
3. Added the missing opening bracket
4. Removed newlines after case statements

BTW, I had a query -> How did the Haiku developers settle on this codestyle (If this is not the right place to ask stuff like this, do tell me where I can do that)(IRC maybe)

2023-03-15 17:39 UTC, humdingerb approved these changes

2023-03-15 17:48 UTC, humdingerb commented
> BTW, I had a query -> How did the Haiku developers settle on this codestyle (If this is not the right place to ask stuff like this, do tell me where I can do that)(IRC maybe)

Well, when many people work on a large project for a long time, there needs to be a style guide. The main developers agreed upon the rules very quickly and it changed only very little after that. While the HaikuArchives projects aren't strictly held to these style rules, it is a huge advantage to try have everyone adopt it. Makes it easy to contribute to any project without having to relearn a new style, or god-forbid,everyone doing their own thing and the code becoming a huge smorgasbord of styles...

I'll merge this for now. If it turns out you can't continue working on the open issues, and nobody else does, we can revert the changes.

In the future, please use a feature branch and squash your commits to sensible code bites.

2023-03-15 17:50 UTC, merged